language: java
node_js:
  - "4.2.1"
install: mvn clean package -DskipTests=true
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
