language: java
jdk:
    - oraclejdk8
node_js:
  - "4.2.1"
sudo: false
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - mvn test
  - npm install -g bower
  - bower install
  - grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
